config/routes.rb
Rails.application.routes.draw do
  resources :words, except: [:show]
  root to: 'application#index'
end

app/models/board.rb
class Board
  BOARD_SIZE = 24

  def initialize
    @phrase_bank = Word.pluck(:word).freeze
    @used_words  = []
  end

  def generate
    return [] if phrase_bank.size < BOARD_SIZE
    while used_words.size <= BOARD_SIZE
      word = phrase_bank.sample
      next if used_words.include? word
      used_words.push word
    end
    make_board
  end

  private

  attr_reader :phrase_bank, :used_words

  def make_board
    [
        used_words[0..4],
        used_words[5..9],
        used_words[10..13],
        used_words[14..18],
        used_words[19..23]
    ]
  end
end

app/models/word.rb
class Word < ActiveRecord::Base
  validates_uniqueness_of :word, :case_sensitive => false
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def index
    @board = Board.new.generate
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :set_word, only: [:show, :edit, :update, :destroy]

  # GET /words
  # GET /words.json
  def index
    @words = Word.all
  end

  # GET /words/new
  def new
    @word = Word.new
  end

  # GET /words/1/edit
  def edit
  end

  # POST /words
  # POST /words.json
  def create
    @word = Word.new(word_params)

    respond_to do |format|
      if @word.save
        format.html { redirect_to words_url, notice: 'Word was successfully created.' }
        format.json { render :show, status: :created, location: @word }
      else
        format.html { render :new }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /words/1
  # PATCH/PUT /words/1.json
  def update
    respond_to do |format|
      if @word.update(word_params)
        format.html { redirect_to words_url, notice: 'Word was successfully updated.' }
        format.json { render :show, status: :ok, location: @word }
      else
        format.html { render :edit }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /words/1
  # DELETE /words/1.json
  def destroy
    @word.destroy
    respond_to do |format|
      format.html { redirect_to words_url, notice: 'Word was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_word
      @word = Word.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def word_params
      params.require(:word).permit(:word)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/application/index.html.erb
<% if @board.blank? %>
    <h4>Not enough words - needs <%= 24 - Word.count %> more words to make a card</h4>
    <%= link_to 'Edit Words', words_path, class: 'btn' %>
<% else %>
    <div class="btn-group" role="group" aria-label="Controls">
      <%= link_to 'New Board', root_path, class: 'btn' %>
      <a href="#" class="btn" onclick="window.print();return false;">Print Board</a>
      <%= link_to 'Edit Words', words_path, class: 'btn' %>
    </div>

    <table id="meeting_bingo">
      <% @board.each do |row| %>
          <% if row.size == 4 %>
              <tr>
                <td>
                  <%= row[0] %>
                </td>
                <td>
                  <%= row[1] %>
                </td>
                <td>
                  <%= image_tag('nomoremeetings.png') %>
                </td>
                <td>
                  <%= row[2] %>
                </td>
                <td>
                  <%= row[3] %>
                </td>
              </tr>
          <% else %>
              <tr>
                <td>
                  <%= row[0] %>
                </td>
                <td>
                  <%= row[1] %>
                </td>
                <td>
                  <%= row[2] %>
                </td>
                <td>
                  <%= row[3] %>
                </td>
                <td>
                  <%= row[4] %>
                </td>
              </tr>
          <% end %>
      <% end %>
    </table>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MeetingBingo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/words/_form.html.erb
<%= form_for(@word) do |f| %>
  <% if @word.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@word.errors.count, "error") %> prohibited this word from being saved:</h2>

      <ul>
      <% @word.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :word %><br>
    <%= f.text_field :word %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/words/edit.html.erb
<h1>Editing Word</h1>

<%= render 'form' %>

<%= link_to 'Show', @word %> |
<%= link_to 'Back', words_path %>

app/views/words/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Words</h1>

<% if Word.count < 24 %>
    <h4>Not enough words - needs <%= 24 - Word.count %> more words to make a card</h4>
<% else %>
    <%= link_to 'Generate Board', root_path, class: 'btn' %>
<% end %>

<%= link_to 'New Word', new_word_path, class: 'btn' %>

<table>
  <thead>
  <tr>
    <th>Word</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @words.each do |word| %>
      <tr>
        <td><%= word.word %></td>
        <td><%= link_to 'Edit', edit_word_path(word), class: 'btn' %></td>
        <td><%= link_to 'Delete', word, method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn' %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

app/views/words/new.html.erb
<h1>New Word</h1>

<%= render 'form' %>

<%= link_to 'Back', words_path %>

app/views/words/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Word:</strong>
  <%= @word.word %>
</p>

<%= link_to 'Edit', edit_word_path(@word) %> |
<%= link_to 'Back', words_path %>